export const PREGUNTAS = [
  { pregunta: "¿Cuál es el planeta más grande del sistema solar?", opciones: ["Marte", "Júpiter", "Saturno", "Tierra"], correcta: 1 },
  { pregunta: "¿En qué año llegó el ser humano a la Luna?", opciones: ["1965", "1969", "1972", "1959"], correcta: 1 },
  { pregunta: "¿Cuál es el océano más grande del mundo?", opciones: ["Atlántico", "Índico", "Pacífico", "Ártico"], correcta: 2 },
  { pregunta: "¿Cuántos huesos tiene el cuerpo humano adulto?", opciones: ["186", "206", "220", "250"], correcta: 1 },
  { pregunta: "¿Qué gas respiramos principalmente para vivir?", opciones: ["Oxígeno", "Hidrógeno", "Nitrógeno", "Dióxido de carbono"], correcta: 0 },
  { pregunta: "¿Cuál es el país más grande del mundo por territorio?", opciones: ["China", "Canadá", "Rusia", "Brasil"], correcta: 2 },
  { pregunta: "¿Cuál es el río más caudaloso de Sudamérica?", opciones: ["Orinoco", "Amazonas", "Paraná", "Magdalena"], correcta: 1 },
  { pregunta: "¿Quién pintó la Mona Lisa?", opciones: ["Miguel Ángel", "Rafael", "Leonardo da Vinci", "Botticelli"], correcta: 2 },
  { pregunta: "¿Qué elemento químico se representa con el símbolo Au?", opciones: ["Plata", "Oro", "Aluminio", "Argón"], correcta: 1 },
  { pregunta: "¿Cuántos lados tiene un hexágono?", opciones: ["Cinco", "Seis", "Siete", "Ocho"], correcta: 1 },
  { pregunta: "¿En qué continente se encuentra Egipto?", opciones: ["Asia", "Europa", "África", "Oceanía"], correcta: 2 },
  { pregunta: "¿Cuál es el animal terrestre más veloz?", opciones: ["León", "Guepardo", "Caballo", "Antílope"], correcta: 1 },
  { pregunta: "¿Cuál es la capital de Japón?", opciones: ["Osaka", "Kioto", "Tokio", "Nagoya"], correcta: 2 },
  { pregunta: "¿Cuántos jugadores de un mismo equipo están en el campo durante un partido de fútbol?", opciones: ["Nueve", "Diez", "Once", "Doce"], correcta: 2 },
  { pregunta: "¿Qué órgano se encarga de bombear la sangre en el cuerpo humano?", opciones: ["Pulmón", "Hígado", "Riñón", "Corazón"], correcta: 3 },
  { pregunta: "¿Cuál es el planeta más cercano al Sol?", opciones: ["Venus", "Mercurio", "Marte", "Tierra"], correcta: 1 },
  { pregunta: "¿Quién escribió \"Don Quijote de la Mancha\"?", opciones: ["Lope de Vega", "Miguel de Cervantes", "Francisco de Quevedo", "Gabriel García Márquez"], correcta: 1 },
  { pregunta: "¿Qué metal es líquido a temperatura ambiente?", opciones: ["Plomo", "Estaño", "Mercurio", "Zinc"], correcta: 2 },
  { pregunta: "¿En qué año comenzó la Primera Guerra Mundial?", opciones: ["1905", "1914", "1918", "1939"], correcta: 1 },
  { pregunta: "¿Cuál es la capital de Australia?", opciones: ["Sídney", "Melbourne", "Canberra", "Perth"], correcta: 2 },
  { pregunta: "¿Cuántos minutos hay en una hora y media?", opciones: ["75", "80", "90", "100"], correcta: 2 },
  { pregunta: "¿Cuál es el hueso más largo del cuerpo humano?", opciones: ["Húmero", "Fémur", "Tibia", "Radio"], correcta: 1 },
  { pregunta: "¿Cuál es el símbolo químico del agua?", opciones: ["H2O", "CO2", "O2", "NaCl"], correcta: 0 },
  { pregunta: "¿Qué planeta es conocido como el planeta rojo?", opciones: ["Júpiter", "Venus", "Marte", "Saturno"], correcta: 2 },
  { pregunta: "¿Cuál es el elemento de mayor número atómico que existe de forma natural en cantidades apreciables en la Tierra?", opciones: ["Plutonio", "Torio", "Uranio", "Neptunio"], correcta: 2 },
  { pregunta: "¿Qué partícula mediadora transmite la fuerza nuclear fuerte entre quarks?", opciones: ["Fotón", "Bosón W", "Gluón", "Gravitón"], correcta: 2 },
  { pregunta: "¿Cuál es el valor aproximado de la constante de estructura fina?", opciones: ["1/273", "1/137", "1/108", "1/1836"], correcta: 1 },
  { pregunta: "¿Qué físico formuló el principio de exclusión para los electrones en un átomo?", opciones: ["Heisenberg", "Paul Dirac", "Wolfgang Pauli", "Enrico Fermi"], correcta: 2 },
  { pregunta: "¿Cuál es la temperatura exacta del punto triple del agua en kelvin?", opciones: ["273,15 K", "273,16 K", "273,00 K", "277,13 K"], correcta: 1 },
  { pregunta: "¿Qué metal tiene el punto de fusión más alto de todos?", opciones: ["Osmio", "Renio", "Tungsteno", "Tántalo"], correcta: 2 },
  { pregunta: "¿Cuál es el elemento más electronegativo de la tabla periódica?", opciones: ["Flúor", "Oxígeno", "Cloro", "Nitrógeno"], correcta: 0 },
  { pregunta: "¿Cómo se llama la temperatura por encima de la cual un material ferromagnético pierde su magnetismo?", opciones: ["Temperatura de Debye", "Temperatura de Fermi", "Punto de Boyle", "Punto de Curie"], correcta: 3 },
  { pregunta: "¿Qué enzima une los fragmentos de Okazaki durante la replicación del ADN?", opciones: ["ADN ligasa", "ADN polimerasa I", "Helicasa", "Primasa"], correcta: 0 },
  { pregunta: "¿Cuántos cromosomas tiene un gato doméstico en sus células somáticas?", opciones: ["32", "38", "46", "78"], correcta: 1 },
  { pregunta: "Además de la mitocondria, ¿qué organelo celular posee su propio ADN?", opciones: ["Cloroplasto", "Ribosoma", "Lisosoma", "Aparato de Golgi"], correcta: 0 },
  { pregunta: "¿Cuál de estos procesos ocurre en la matriz mitocondrial?", opciones: ["Ciclo de Krebs", "Glucólisis", "Ciclo de Calvin", "Ciclo de Cori"], correcta: 0 },
  { pregunta: "¿Qué científica determinó por cristalografía la estructura de la penicilina y de la vitamina B12?", opciones: ["Rosalind Franklin", "Marie Curie", "Dorothy Hodgkin", "Barbara McClintock"], correcta: 2 },
  { pregunta: "¿Cuál es la velocidad de escape de la Tierra, aproximadamente?", opciones: ["7,9 km/s", "16,7 km/s", "29,8 km/s", "11,2 km/s"], correcta: 3 },
  { pregunta: "¿Qué luna de Saturno es la única del sistema solar con una atmósfera densa?", opciones: ["Encélado", "Titán", "Rea", "Jápeto"], correcta: 1 },
  { pregunta: "¿Cuál es la estrella más cercana al Sol?", opciones: ["Alfa Centauri A", "Sirio", "Próxima Centauri", "Estrella de Barnard"], correcta: 2 },
  { pregunta: "¿Cómo se llama el límite de masa por encima del cual una enana blanca colapsa?", opciones: ["Límite de Tolman-Oppenheimer-Volkoff", "Radio de Schwarzschild", "Límite de Chandrasekhar", "Límite de Eddington"], correcta: 2 },
  { pregunta: "¿Cuál es la luna más grande de Neptuno?", opciones: ["Nereida", "Proteo", "Tritón", "Larissa"], correcta: 2 },
  { pregunta: "¿Qué telescopio espacial descubrió miles de exoplanetas con el método de tránsito entre 2009 y 2018?", opciones: ["Hubble", "Kepler", "Spitzer", "TESS"], correcta: 1 },
  { pregunta: "¿En qué año se descubrió Plutón?", opciones: ["1915", "1930", "1946", "1951"], correcta: 1 },
  { pregunta: "¿Cuál es el valor aproximado de la constante de Avogadro?", opciones: ["6,626 × 10^-34", "1,602 × 10^-19", "6,022 × 10^23", "9,109 × 10^-31"], correcta: 2 },
  { pregunta: "¿Qué ave viva tiene la mayor envergadura de alas?", opciones: ["Cóndor andino", "Pelícano dálmata", "Albatros errante", "Marabú"], correcta: 2 },
  { pregunta: "¿Qué animal tiene tres corazones?", opciones: ["Medusa", "Estrella de mar", "Pulpo", "Cangrejo"], correcta: 2 },
  { pregunta: "¿Cuál es el hueso más pequeño del cuerpo humano?", opciones: ["Martillo", "Estribo", "Yunque", "Hioides"], correcta: 1 },
  { pregunta: "¿Cuál es el nervio craneal más largo?", opciones: ["Facial", "Trigémino", "Glosofaríngeo", "Vago"], correcta: 3 },
  { pregunta: "¿Qué científico descubrió el sistema de grupos sanguíneos ABO?", opciones: ["Louis Pasteur", "Robert Koch", "Karl Landsteiner", "Paul Ehrlich"], correcta: 2 },
  { pregunta: "¿Cuál es el elemento más abundante en la corteza terrestre?", opciones: ["Silicio", "Oxígeno", "Aluminio", "Hierro"], correcta: 1 },
  { pregunta: "¿Qué mineral tiene dureza 7 en la escala de Mohs?", opciones: ["Topacio", "Ortoclasa", "Cuarzo", "Corindón"], correcta: 2 },
  { pregunta: "¿Cómo se llama la discontinuidad que separa la corteza del manto terrestre?", opciones: ["Gutenberg", "Lehmann", "Mohorovičić", "Conrad"], correcta: 2 },
  { pregunta: "¿Qué escala mide la intensidad de un sismo según sus efectos observados y no su energía?", opciones: ["Richter", "Mercalli", "Beaufort", "Saffir-Simpson"], correcta: 1 },
  { pregunta: "¿Cuál es el gas más abundante en la atmósfera de Venus?", opciones: ["Nitrógeno", "Dióxido de carbono", "Ácido sulfúrico", "Argón"], correcta: 1 },
  { pregunta: "¿Cómo se llama el punto más profundo conocido de los océanos?", opciones: ["Fosa de Puerto Rico", "Fosa de Java", "Fosa de Tonga", "Abismo Challenger"], correcta: 3 },
  { pregunta: "¿Cuál es el desierto más grande del mundo, contando los polares?", opciones: ["Sahara", "Antártico", "Gobi", "Arábigo"], correcta: 1 },
  { pregunta: "¿Cuál es el lago más profundo del mundo?", opciones: ["Baikal", "Tanganica", "Superior", "Titicaca"], correcta: 0 },
  { pregunta: "¿Cuál es el río más largo de Europa?", opciones: ["Danubio", "Rin", "Dniéper", "Volga"], correcta: 3 },
  { pregunta: "¿Qué país tiene más husos horarios en total, contando sus territorios de ultramar?", opciones: ["Rusia", "Estados Unidos", "Francia", "Reino Unido"], correcta: 2 },
  { pregunta: "¿Cuál es la capital de Burkina Faso?", opciones: ["Uagadugú", "Bamako", "Niamey", "Acra"], correcta: 0 },
  { pregunta: "¿Cuál es la capital de Kazajistán?", opciones: ["Astaná", "Almaty", "Taskent", "Biskek"], correcta: 0 },
  { pregunta: "¿Cuál es la capital de Bután?", opciones: ["Timbu", "Katmandú", "Daca", "Colombo"], correcta: 0 },
  { pregunta: "¿Cuál es la capital de Surinam?", opciones: ["Georgetown", "Paramaribo", "Cayena", "Montevideo"], correcta: 1 },
  { pregunta: "¿Cuál es la capital de Mongolia?", opciones: ["Astaná", "Biskek", "Dusambé", "Ulán Bator"], correcta: 3 },
  { pregunta: "¿Cuál es el país más pequeño de África por superficie?", opciones: ["Seychelles", "Gambia", "Mauricio", "Comoras"], correcta: 0 },
  { pregunta: "¿Qué estrecho separa Sicilia de la Italia continental?", opciones: ["Mesina", "Bonifacio", "Otranto", "Gibraltar"], correcta: 0 },
  { pregunta: "¿Cuál es el volcán más alto del mundo sobre el nivel del mar?", opciones: ["Cotopaxi", "Ojos del Salado", "Kilimanjaro", "Popocatépetl"], correcta: 1 },
  { pregunta: "¿Cuál es la isla más grande del mar Mediterráneo?", opciones: ["Cerdeña", "Chipre", "Sicilia", "Creta"], correcta: 2 },
  { pregunta: "¿En qué año cayó Constantinopla en manos de los otomanos?", opciones: ["1204", "1492", "1389", "1453"], correcta: 3 },
  { pregunta: "¿Quién fue el primer emperador de Roma?", opciones: ["Augusto", "Julio César", "Tiberio", "Nerón"], correcta: 0 },
  { pregunta: "¿En qué año se firmó la Paz de Westfalia que cerró la Guerra de los Treinta Años?", opciones: ["1555", "1713", "1815", "1648"], correcta: 3 },
  { pregunta: "¿Qué tratado dividió el Nuevo Mundo entre España y Portugal en 1494?", opciones: ["Tordesillas", "Utrecht", "Verdún", "Versalles"], correcta: 0 },
  { pregunta: "¿Quién fue el último zar de Rusia?", opciones: ["Alejandro III", "Nicolás II", "Pedro III", "Alejandro II"], correcta: 1 },
  { pregunta: "¿Qué dinastía gobernaba China cuando Marco Polo la visitó?", opciones: ["Song", "Ming", "Tang", "Yuan"], correcta: 3 },
  { pregunta: "¿Qué rey inglés firmó la Carta Magna en 1215?", opciones: ["Juan sin Tierra", "Ricardo Corazón de León", "Enrique II", "Eduardo I"], correcta: 0 },
  { pregunta: "¿Cuál fue la capital del Imperio inca?", opciones: ["Machu Picchu", "Quito", "Cusco", "Cajamarca"], correcta: 2 },
  { pregunta: "¿Qué civilización construyó la ciudad de Tiahuanaco, junto al lago Titicaca?", opciones: ["Chavín", "Tiwanaku", "Nazca", "Moche"], correcta: 1 },
  { pregunta: "¿En qué año murió Alejandro Magno?", opciones: ["323 a. C.", "356 a. C.", "331 a. C.", "300 a. C."], correcta: 0 },
  { pregunta: "¿En qué batalla aniquiló Aníbal a un ejército romano en el año 216 a. C.?", opciones: ["Cannas", "Zama", "Trasimeno", "Metauro"], correcta: 0 },
  { pregunta: "¿Quién fue el primer presidente de México?", opciones: ["Agustín de Iturbide", "Guadalupe Victoria", "Vicente Guerrero", "Benito Juárez"], correcta: 1 },
  { pregunta: "¿En qué año se promulgó la Constitución mexicana que sigue vigente?", opciones: ["1857", "1917", "1910", "1824"], correcta: 1 },
  { pregunta: "¿Qué tratado puso fin a la guerra entre México y Estados Unidos en 1848?", opciones: ["Tratado de Córdoba", "Tratado de la Mesilla", "Tratado de Guadalupe Hidalgo", "Tratados de Velasco"], correcta: 2 },
  { pregunta: "¿Quién fue el último tlatoani de Tenochtitlan?", opciones: ["Cuauhtémoc", "Moctezuma II", "Cuitláhuac", "Itzcóatl"], correcta: 0 },
  { pregunta: "¿En qué año se fundó México-Tenochtitlan según la tradición?", opciones: ["1325", "1428", "1492", "1200"], correcta: 0 },
  { pregunta: "¿Qué cultura es considerada la cultura madre de Mesoamérica?", opciones: ["Teotihuacana", "Zapoteca", "Tolteca", "Olmeca"], correcta: 3 },
  { pregunta: "¿Quién lideró la primera fase de la Revolución haitiana?", opciones: ["Toussaint Louverture", "Jean-Jacques Dessalines", "Henri Christophe", "Alexandre Pétion"], correcta: 0 },
  { pregunta: "¿Qué papa convocó la Primera Cruzada en 1095?", opciones: ["Gregorio VII", "Inocencio III", "Urbano II", "León X"], correcta: 2 },
  { pregunta: "¿En qué año ocurrió el Cisma de Oriente entre las Iglesias católica y ortodoxa?", opciones: ["800", "1204", "1378", "1054"], correcta: 3 },
  { pregunta: "¿Qué emperador romano instauró la tetrarquía?", opciones: ["Constantino", "Adriano", "Diocleciano", "Teodosio"], correcta: 2 },
  { pregunta: "¿Quién fue el último emperador del Imperio romano de Occidente?", opciones: ["Rómulo Augústulo", "Odoacro", "Honorio", "Justiniano"], correcta: 0 },
  { pregunta: "¿Qué batalla del año 732 detuvo el avance musulmán hacia el norte de Francia?", opciones: ["Hastings", "Lepanto", "Guadalete", "Poitiers"], correcta: 3 },
  { pregunta: "¿En qué año se libró la batalla naval de Lepanto?", opciones: ["1492", "1588", "1571", "1609"], correcta: 2 },
  { pregunta: "¿En qué año ocurrió el Gran Incendio de Londres?", opciones: ["1605", "1688", "1707", "1666"], correcta: 3 },
  { pregunta: "¿Quién fue el canciller que lideró la unificación alemana de 1871?", opciones: ["Bismarck", "Metternich", "Hindenburg", "Brandt"], correcta: 0 },
  { pregunta: "¿En qué año se disolvió formalmente la Unión Soviética?", opciones: ["1991", "1989", "1990", "1993"], correcta: 0 },
  { pregunta: "¿Qué conferencia de 1884-1885 reguló el reparto colonial de África?", opciones: ["Viena", "Yalta", "Versalles", "Berlín"], correcta: 3 },
  { pregunta: "¿Quién fue el primer secretario general de la ONU?", opciones: ["Dag Hammarskjöld", "U Thant", "Trygve Lie", "Kofi Annan"], correcta: 2 },
  { pregunta: "¿En qué año se fundó la Cruz Roja?", opciones: ["1881", "1901", "1863", "1919"], correcta: 2 },
  { pregunta: "¿Qué faraón mandó construir la Gran Pirámide de Guiza?", opciones: ["Kefrén", "Micerino", "Zoser", "Keops"], correcta: 3 },
  { pregunta: "¿Qué faraón impuso el culto a Atón?", opciones: ["Ramsés II", "Akenatón", "Tutmosis III", "Seti I"], correcta: 1 },
  { pregunta: "¿Quién descifró los jeroglíficos egipcios en 1822?", opciones: ["Thomas Young", "Howard Carter", "Flinders Petrie", "Jean-François Champollion"], correcta: 3 },
  { pregunta: "¿Qué escritura antigua descifró Michael Ventris en 1952?", opciones: ["Lineal B", "Lineal A", "Cuneiforme", "Rongorongo"], correcta: 0 },
  { pregunta: "¿Qué imperio africano gobernó Mansa Musa?", opciones: ["Songhai", "Mali", "Ghana", "Kanem"], correcta: 1 },
  { pregunta: "¿Qué pueblo fundó la ciudad de Cartago?", opciones: ["Fenicios", "Griegos", "Etruscos", "Egipcios"], correcta: 0 },
  { pregunta: "¿Quién fue el primer shogun del shogunato Tokugawa?", opciones: ["Tokugawa Ieyasu", "Oda Nobunaga", "Toyotomi Hideyoshi", "Minamoto no Yoritomo"], correcta: 0 },
  { pregunta: "¿En qué año comenzó la Restauración Meiji en Japón?", opciones: ["1853", "1868", "1894", "1905"], correcta: 1 },
  { pregunta: "¿Qué dinastía construyó la mayor parte de la Gran Muralla china que se conserva hoy?", opciones: ["Qin", "Ming", "Han", "Qing"], correcta: 1 },
  { pregunta: "¿Qué guerra terminó con el Tratado de Nankín de 1842?", opciones: ["Guerra de los Bóxers", "Primera Guerra Sino-Japonesa", "Primera Guerra del Opio", "Rebelión Taiping"], correcta: 2 },
  { pregunta: "¿Qué rey de Prusia es conocido como el Grande?", opciones: ["Federico Guillermo I", "Guillermo I", "Federico III", "Federico II"], correcta: 3 },
  { pregunta: "¿Quién fue el tercer presidente de Estados Unidos?", opciones: ["John Adams", "James Madison", "Thomas Jefferson", "James Monroe"], correcta: 2 },
  { pregunta: "¿Qué presidente de EE. UU. sirvió dos mandatos no consecutivos?", opciones: ["Theodore Roosevelt", "Andrew Johnson", "Martin Van Buren", "Grover Cleveland"], correcta: 3 },
  { pregunta: "¿Qué batalla de 1862 fue el día más sangriento de la historia militar de Estados Unidos?", opciones: ["Gettysburg", "Shiloh", "Antietam", "Bull Run"], correcta: 2 },
  { pregunta: "¿Quién escribió la novela Pedro Páramo?", opciones: ["Carlos Fuentes", "Octavio Paz", "Juan José Arreola", "Juan Rulfo"], correcta: 3 },
  { pregunta: "¿Quién escribió la novela Rayuela?", opciones: ["Mario Vargas Llosa", "Jorge Luis Borges", "Ernesto Sabato", "Julio Cortázar"], correcta: 3 },
  { pregunta: "¿Quién escribió La región más transparente?", opciones: ["Juan Rulfo", "Octavio Paz", "Carlos Fuentes", "Elena Poniatowska"], correcta: 2 },
  { pregunta: "¿Quién ganó el Premio Nobel de Literatura en 1990?", opciones: ["Gabriel García Márquez", "Pablo Neruda", "Octavio Paz", "Camilo José Cela"], correcta: 2 },
  { pregunta: "¿Quién ganó el Premio Nobel de Literatura en 1982?", opciones: ["Mario Vargas Llosa", "Octavio Paz", "Gabriel García Márquez", "Miguel Ángel Asturias"], correcta: 2 },
  { pregunta: "¿Quién ganó el Premio Nobel de Literatura en 1967?", opciones: ["Pablo Neruda", "Gabriela Mistral", "Miguel Ángel Asturias", "Jorge Luis Borges"], correcta: 2 },
  { pregunta: "¿Quién fue la primera persona latinoamericana en ganar el Nobel de Literatura?", opciones: ["Sor Juana Inés de la Cruz", "Gabriela Mistral", "Isabel Allende", "Rosario Castellanos"], correcta: 1 },
  { pregunta: "¿Quién escribió Almas muertas?", opciones: ["Tolstói", "Gógol", "Turguénev", "Chéjov"], correcta: 1 },
  { pregunta: "¿Quién escribió En busca del tiempo perdido?", opciones: ["Marcel Proust", "Flaubert", "Albert Camus", "Balzac"], correcta: 0 },
  { pregunta: "¿Quién escribió Ulises (1922)?", opciones: ["James Joyce", "Virginia Woolf", "Samuel Beckett", "T. S. Eliot"], correcta: 0 },
  { pregunta: "¿Quién escribió El corazón de las tinieblas?", opciones: ["Rudyard Kipling", "Joseph Conrad", "Graham Greene", "E. M. Forster"], correcta: 1 },
  { pregunta: "¿Quién escribió La montaña mágica?", opciones: ["Hermann Hesse", "Thomas Mann", "Franz Kafka", "Robert Musil"], correcta: 1 },
  { pregunta: "¿Quién escribió El lobo estepario?", opciones: ["Thomas Mann", "Rainer Maria Rilke", "Bertolt Brecht", "Hermann Hesse"], correcta: 3 },
  { pregunta: "¿Quién escribió Los hermanos Karamázov?", opciones: ["Tolstói", "Pasternak", "Dostoievski", "Bulgákov"], correcta: 2 },
  { pregunta: "¿Quién escribió El maestro y Margarita?", opciones: ["Pasternak", "Bulgákov", "Gorki", "Solzhenitsyn"], correcta: 1 },
  { pregunta: "¿Cuántos círculos tiene el Infierno en la Divina Comedia de Dante?", opciones: ["9", "7", "10", "12"], correcta: 0 },
  { pregunta: "¿Quién escribió El paraíso perdido?", opciones: ["John Donne", "William Blake", "Alexander Pope", "John Milton"], correcta: 3 },
  { pregunta: "¿En qué obra de Shakespeare aparece el personaje de Yago?", opciones: ["Macbeth", "El rey Lear", "Hamlet", "Otelo"], correcta: 3 },
  { pregunta: "¿Quién pintó Las Meninas?", opciones: ["Velázquez", "Goya", "El Greco", "Murillo"], correcta: 0 },
  { pregunta: "¿Quién pintó El jardín de las delicias?", opciones: ["Brueghel", "Durero", "Van Eyck", "El Bosco"], correcta: 3 },
  { pregunta: "¿Quién pintó La ronda de noche?", opciones: ["Rembrandt",
