export const PREGUNTAS = [
  { pregunta: "¿Cuál es el planeta más grande del sistema solar?", opciones: ["Marte", "Júpiter", "Saturno", "Tierra"], correcta: 1 },
  { pregunta: "¿En qué año llegó el ser humano a la Luna?", opciones: ["1965", "1969", "1972", "1959"], correcta: 1 },
  { pregunta: "¿Cuál es el océano más grande del mundo?", opciones: ["Atlántico", "Índico", "Pacífico", "Ártico"], correcta: 2 },
  { pregunta: "¿Cuántos huesos tiene el cuerpo humano adulto?", opciones: ["186", "206", "220", "250"], correcta: 1 },
  { pregunta: "¿Qué gas respiramos principalmente para vivir?", opciones: ["Oxígeno", "Hidrógeno", "Nitrógeno", "Dióxido de carbono"], correcta: 0 },
  { pregunta: "¿Cuál es el país más grande del mundo por territorio?", opciones: ["China", "Canadá", "Rusia", "Brasil"], correcta: 2 },
  { pregunta: "¿Cuál es el río más caudaloso de Sudamérica?", opciones: ["Orinoco", "Amazonas", "Paraná", "Magdalena"], correcta: 1 },
  { pregunta: "¿Quién pintó la Mona Lisa?", opciones: ["Miguel Ángel", "Rafael", "Leonardo da Vinci", "Botticelli"], correcta: 2 },
  { pregunta: "¿Qué elemento químico se representa con el símbolo Au?", opciones: ["Plata", "Oro", "Aluminio", "Argón"], correcta: 1 },
  { pregunta: "¿Cuántos lados tiene un hexágono?", opciones: ["Cinco", "Seis", "Siete", "Ocho"], correcta: 1 },
  { pregunta: "¿En qué continente se encuentra Egipto?", opciones: ["Asia", "Europa", "África", "Oceanía"], correcta: 2 },
  { pregunta: "¿Cuál es el animal terrestre más veloz?", opciones: ["León", "Guepardo", "Caballo", "Antílope"], correcta: 1 },
  { pregunta: "¿Cuál es la capital de Japón?", opciones: ["Osaka", "Kioto", "Tokio", "Nagoya"], correcta: 2 },
  { pregunta: "¿Cuántos jugadores de un mismo equipo están en el campo durante un partido de fútbol?", opciones: ["Nueve", "Diez", "Once", "Doce"], correcta: 2 },
  { pregunta: "¿Qué órgano se encarga de bombear la sangre en el cuerpo humano?", opciones: ["Pulmón", "Hígado", "Riñón", "Corazón"], correcta: 3 },
  { pregunta: "¿Cuál es el planeta más cercano al Sol?", opciones: ["Venus", "Mercurio", "Marte", "Tierra"], correcta: 1 },
  { pregunta: "¿Quién escribió \"Don Quijote de la Mancha\"?", opciones: ["Lope de Vega", "Miguel de Cervantes", "Francisco de Quevedo", "Gabriel García Márquez"], correcta: 1 },
  { pregunta: "¿Qué metal es líquido a temperatura ambiente?", opciones: ["Plomo", "Estaño", "Mercurio", "Zinc"], correcta: 2 },
  { pregunta: "¿En qué año comenzó la Primera Guerra Mundial?", opciones: ["1905", "1914", "1918", "1939"], correcta: 1 },
  { pregunta: "¿Cuál es la capital de Australia?", opciones: ["Sídney", "Melbourne", "Canberra", "Perth"], correcta: 2 },
  { pregunta: "¿Cuántos minutos hay en una hora y media?", opciones: ["75", "80", "90", "100"], correcta: 2 },
  { pregunta: "¿Cuál es el hueso más largo del cuerpo humano?", opciones: ["Húmero", "Fémur", "Tibia", "Radio"], correcta: 1 },
  { pregunta: "¿Cuál es el símbolo químico del agua?", opciones: ["H2O", "CO2", "O2", "NaCl"], correcta: 0 },
  { pregunta: "¿Qué planeta es conocido como el planeta rojo?", opciones: ["Júpiter", "Venus", "Marte", "Saturno"], correcta: 2 },
  { pregunta: "¿Cuál es la capital de Francia?", opciones: ["Lyon", "París", "Marsella", "Niza"], correcta: 1 },
  { pregunta: "¿Cuál es la capital de Argentina?", opciones: ["Córdoba", "Rosario", "Buenos Aires", "Mendoza"], correcta: 2 },
  { pregunta: "¿Cuál es la capital de México?", opciones: ["Guadalajara", "Ciudad de México", "Monterrey", "Puebla"], correcta: 1 },
  { pregunta: "¿Cuál es la capital de Brasil?", opciones: ["Río de Janeiro", "São Paulo", "Brasilia", "Salvador"], correcta: 2 },
  { pregunta: "¿Cuál es la capital de Canadá?", opciones: ["Toronto", "Ottawa", "Vancouver", "Montreal"], correcta: 1 },
  { pregunta: "¿Cuál es la capital de Alemania?", opciones: ["Múnich", "Hamburgo", "Berlín", "Fráncfort"], correcta: 2 },
  { pregunta: "¿Cuál es la capital de España?", opciones: ["Barcelona", "Madrid", "Sevilla", "Valencia"], correcta: 1 },
  { pregunta: "¿Cuál es la capital de Egipto?", opciones: ["Alejandría", "El Cairo", "Luxor", "Guiza"], correcta: 1 },
  { pregunta: "¿Qué país tiene forma de bota en Europa?", opciones: ["España", "Grecia", "Italia", "Portugal"], correcta: 2 },
  { pregunta: "¿Cuál es el país más pequeño del mundo?", opciones: ["Mónaco", "Ciudad del Vaticano", "San Marino", "Liechtenstein"], correcta: 1 },
  { pregunta: "¿Cuál es la montaña más alta del mundo sobre el nivel del mar?", opciones: ["K2", "Everest", "Kilimanjaro", "Aconcagua"], correcta: 1 },
  { pregunta: "¿Cuál es el desierto cálido más grande del mundo?", opciones: ["Gobi", "Sahara", "Kalahari", "Atacama"], correcta: 1 },
  { pregunta: "¿Cuántos continentes se consideran comúnmente en el mundo?", opciones: ["Cinco", "Seis", "Siete", "Ocho"], correcta: 2 },
  { pregunta: "¿Cuál es el punto cardinal opuesto al norte?", opciones: ["Este", "Oeste", "Sur", "Noreste"], correcta: 2 },
  { pregunta: "¿En qué país está el Taj Mahal?", opciones: ["Pakistán", "India", "Nepal", "Bangladés"], correcta: 1 },
  { pregunta: "¿Cuál es el animal más grande del mundo?", opciones: ["Elefante africano", "Tiburón ballena", "Ballena azul", "Jirafa"], correcta: 2 },
  { pregunta: "¿Qué planeta es famoso por sus anillos visibles?", opciones: ["Júpiter", "Saturno", "Marte", "Mercurio"], correcta: 1 },
  { pregunta: "¿Cuál es el símbolo químico del hierro?", opciones: ["Fl", "Fe", "Fr", "Hi"], correcta: 1 },
  { pregunta: "¿Cuál es el símbolo químico del sodio?", opciones: ["So", "Na", "Sd", "S"], correcta: 1 },
  { pregunta: "¿Qué gas absorben las plantas para la fotosíntesis?", opciones: ["Oxígeno", "Nitrógeno", "Dióxido de carbono", "Helio"], correcta: 2 },
  { pregunta: "¿Cuál es el órgano más grande del cuerpo humano?", opciones: ["Hígado", "Piel", "Intestino", "Pulmón"], correcta: 1 },
  { pregunta: "¿Cuántos dientes tiene un adulto con todas sus piezas?", opciones: ["28", "30", "32", "36"], correcta: 2 },
  { pregunta: "¿Qué vitamina produce el cuerpo con la luz del sol?", opciones: ["Vitamina A", "Vitamina C", "Vitamina D", "Vitamina K"], correcta: 2 },
  { pregunta: "¿Cuántos corazones tiene un pulpo?", opciones: ["Uno", "Dos", "Tres", "Cuatro"], correcta: 2 },
  { pregunta: "¿Qué mamífero tiene la capacidad de volar?", opciones: ["Murciélago", "Ardilla", "Colibrí", "Pingüino"], correcta: 0 },
  { pregunta: "¿Qué ave no vuela y vive en la Antártida?", opciones: ["Albatros", "Pingüino", "Gaviota", "Cóndor"], correcta: 1 },
  { pregunta: "¿Cuántos días tiene un año bisiesto?", opciones: ["365", "366", "364", "367"], correcta: 1 },
  { pregunta: "¿Cuántos colores tiene el arcoíris?", opciones: ["Cinco", "Seis", "Siete", "Ocho"], correcta: 2 },
  { pregunta: "¿Cuántas horas tiene un día?", opciones: ["12", "24", "36", "48"], correcta: 1 },
  { pregunta: "¿Quién llegó a América en 1492 en el viaje financiado por España?", opciones: ["Américo Vespucio", "Cristóbal Colón", "Hernán Cortés", "Fernando de Magallanes"], correcta: 1 },
  { pregunta: "¿En qué año cayó el Muro de Berlín?", opciones: ["1985", "1989", "1991", "1993"], correcta: 1 },
  { pregunta: "¿En qué año comenzó la Segunda Guerra Mundial?", opciones: ["1936", "1939", "1941", "1945"], correcta: 1 },
  { pregunta: "¿Quién fue el primer presidente de Estados Unidos?", opciones: ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "John Adams"], correcta: 1 },
  { pregunta: "¿Qué civilización construyó Machu Picchu?", opciones: ["Azteca", "Maya", "Inca", "Olmeca"], correcta: 2 },
  { pregunta: "¿Qué civilización construyó Chichén Itzá?", opciones: ["Maya", "Inca", "Azteca", "Tolteca"], correcta: 0 },
  { pregunta: "¿Quién propuso la teoría de la relatividad?", opciones: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Nikola Tesla"], correcta: 1 },
  { pregunta: "¿Quién formuló la ley de la gravitación universal?", opciones: ["Isaac Newton", "Albert Einstein", "Johannes Kepler", "Copérnico"], correcta: 0 },
  { pregunta: "¿Quién escribió \"Cien años de soledad\"?", opciones: ["Mario Vargas Llosa", "Gabriel García Márquez", "Julio Cortázar", "Jorge Luis Borges"], correcta: 1 },
  { pregunta: "¿Quién pintó \"La noche estrellada\"?", opciones: ["Pablo Picasso", "Vincent van Gogh", "Claude Monet", "Salvador Dalí"], correcta: 1 },
  { pregunta: "¿Quién pintó el \"Guernica\"?", opciones: ["Salvador Dalí", "Pablo Picasso", "Diego Rivera", "Joan Miró"], correcta: 1 },
  { pregunta: "¿Qué instrumento musical tiene normalmente seis cuerdas?", opciones: ["Violín", "Guitarra", "Arpa", "Bajo eléctrico"], correcta: 1 },
  { pregunta: "¿Cuál es el idioma con más hablantes nativos del mundo?", opciones: ["Inglés", "Español", "Chino mandarín", "Hindi"], correcta: 2 },
  { pregunta: "¿Cuántos jugadores de un equipo hay en la cancha en baloncesto?", opciones: ["Cuatro", "Cinco", "Seis", "Siete"], correcta: 1 },
  { pregunta: "¿Cada cuántos años se celebra el Mundial de fútbol masculino?", opciones: ["Dos", "Tres", "Cuatro", "Cinco"], correcta: 2 },
  { pregunta: "¿Qué selección ganó el Mundial de Qatar 2022?", opciones: ["Francia", "Argentina", "Brasil", "Croacia"], correcta: 1 },
  { pregunta: "¿Qué deporte se juega en el torneo de Wimbledon?", opciones: ["Bádminton", "Tenis", "Squash", "Pádel"], correcta: 1 },
  { pregunta: "¿Cuántos aros tiene el símbolo olímpico?", opciones: ["Cuatro", "Cinco", "Seis", "Siete"], correcta: 1 },
  { pregunta: "¿Quién creó Facebook?", opciones: ["Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Jeff Bezos"], correcta: 2 },
  { pregunta: "¿Qué significan las siglas WWW?", opciones: ["World Wide Web", "World Web Window", "Wide World Web", "Web World Wide"], correcta: 0 },
  { pregunta: "¿Qué lenguaje de programación se ejecuta de forma nativa en los navegadores web?", opciones: ["Java", "Python", "JavaScript", "C++"], correcta: 2 },
  { pregunta: "¿Qué empresa fabrica el iPhone?", opciones: ["Samsung", "Apple", "Huawei", "Sony"], correcta: 1 },
  { pregunta: "¿Cuántos bits tiene un byte?", opciones: ["Cuatro", "Ocho", "Dieciséis", "Treinta y dos"], correcta: 1 },
  { pregunta: "¿Cuánto es 12 × 12?", opciones: ["124", "132", "144", "154"], correcta: 2 },
  { pregunta: "¿Cuál es la raíz cuadrada de 81?", opciones: ["7", "8", "9", "10"], correcta: 2 },
  { pregunta: "¿Cuántos grados suman los ángulos internos de un triángulo?", opciones: ["90", "180", "270", "360"], correcta: 1 },
  { pregunta: "¿Cuál de estos números es primo?", opciones: ["9", "15", "17", "21"], correcta: 2 }
];
  
