export const PREGUNTAS = [
  { pregunta: "¿Cuál es el planeta más grande del sistema solar?", opciones: ["Marte", "Júpiter", "Saturno", "Tierra"], correcta: 1 },
  { pregunta: "¿En qué año llegó el ser humano a la Luna?", opciones: ["1965", "1969", "1972", "1959"], correcta: 1 },
  { pregunta: "¿Cuál es el océano más grande del mundo?", opciones: ["Atlántico", "Índico", "Pacífico", "Ártico"], correcta: 2 },
  { pregunta: "¿Cuántos huesos tiene el cuerpo humano adulto?", opciones: ["186", "206", "220", "250"], correcta: 1 },
  { pregunta: "¿Qué gas respiramos principalmente para vivir?", opciones: ["Oxígeno", "Hidrógeno", "Nitrógeno", "Dióxido de carbono"], correcta: 0 },
  { pregunta: "¿Cuál es el país más grande del mundo por territorio?", opciones: ["China", "Canadá", "Rusia", "Brasil"], correcta: 2 },
  { pregunta: "¿Cuál es el río más caudaloso de Sudamérica?", opciones: ["Orinoco", "Amazonas", "Paraná", "Magdalena"], correcta: 1 },
  { pregunta: "¿Quién pintó la Mona Lisa?", opciones: ["Miguel Ángel", "Rafael", "Leonardo da Vinci", "Botticelli"], correcta: 2 },
  { pregunta: "¿Qué elemento químico se representa con el símbolo Au?", opciones: ["Plata", "Oro", "Aluminio", "Argón"], correcta: 1 },
  { pregunta: "¿Cuántos lados tiene un hexágono?", opciones: ["Cinco", "Seis", "Siete", "Ocho"], correcta: 1 },
  { pregunta: "¿En qué continente se encuentra Egipto?", opciones: ["Asia", "Europa", "África", "Oceanía"], correcta: 2 },
  { pregunta: "¿Cuál es el animal terrestre más veloz?", opciones: ["León", "Guepardo", "Caballo", "Antílope"], correcta: 1 },
  { pregunta: "¿Cuál es la capital de Japón?", opciones: ["Osaka", "Kioto", "Tokio", "Nagoya"], correcta: 2 },
  { pregunta: "¿Cuántos jugadores de un mismo equipo están en el campo durante un partido de fútbol?", opciones: ["Nueve", "Diez", "Once", "Doce"], correcta: 2 },
  { pregunta: "¿Qué órgano se encarga de bombear la sangre en el cuerpo humano?", opciones: ["Pulmón", "Hígado", "Riñón", "Corazón"], correcta: 3 },
  { pregunta: "¿Cuál es el planeta más cercano al Sol?", opciones: ["Venus", "Mercurio", "Marte", "Tierra"], correcta: 1 },
  { pregunta: "¿Quién escribió \"Don Quijote de la Mancha\"?", opciones: ["Lope de Vega", "Miguel de Cervantes", "Francisco de Quevedo", "Gabriel García Márquez"], correcta: 1 },
  { pregunta: "¿Qué metal es líquido a temperatura ambiente?", opciones: ["Plomo", "Estaño", "Mercurio", "Zinc"], correcta: 2 },
  { pregunta: "¿En qué año comenzó la Primera Guerra Mundial?", opciones: ["1905", "1914", "1918", "1939"], correcta: 1 },
  { pregunta: "¿Cuál es la capital de Australia?", opciones: ["Sídney", "Melbourne", "Canberra", "Perth"], correcta: 2 },
  { pregunta: "¿Cuántos minutos hay en una hora y media?", opciones: ["75", "80", "90", "100"], correcta: 2 },
  { pregunta: "¿Cuál es el hueso más largo del cuerpo humano?", opciones: ["Húmero", "Fémur", "Tibia", "Radio"], correcta: 1 },
  { pregunta: "¿Cuál es el símbolo químico del agua?", opciones: ["H2O", "CO2", "O2", "NaCl"], correcta: 0 },
  { pregunta: "¿Qué planeta es conocido como el planeta rojo?", opciones: ["Júpiter", "Venus", "Marte", "Saturno"], correcta: 2 },
  { pregunta: "¿Cuál es el elemento de mayor número atómico que existe de forma natural en cantidades apreciables en la Tierra?", opciones: ["Plutonio", "Torio", "Uranio", "Neptunio"], correcta: 2 },
  { pregunta: "¿Qué partícula mediadora transmite la fuerza nuclear fuerte entre quarks?", opciones: ["Fotón", "Bosón W", "Gluón", "Gravitón"], correcta: 2 },
  { pregunta: "¿Cuál es el valor aproximado de la constante de estructura fina?", opciones: ["1/273", "1/137", "1/108", "1/1836"], correcta: 1 },
  { pregunta: "¿Qué físico formuló el principio de exclusión para los electrones en un átomo?", opciones: ["Heisenberg", "Paul Dirac", "Wolfgang Pauli", "Enrico Fermi"], correcta: 2 },
  { pregunta: "¿Cuál es la temperatura exacta del punto triple del agua en kelvin?", opciones: ["273,15 K", "273,16 K", "273,00 K", "277,13 K"], correcta: 1 },
  { pregunta: "¿Qué metal tiene el punto de fusión más alto de todos?", opciones: ["Osmio", "Renio", "Tungsteno", "Tántalo"], correcta: 2 },
  { pregunta: "¿Cuál es el elemento más electronegativo de la tabla periódica?", opciones: ["Flúor", "Oxígeno", "Cloro", "Nitrógeno"], correcta: 0 },
  { pregunta: "¿Cómo se llama la temperatura por encima de la cual un material ferromagnético pierde su magnetismo?", opciones: ["Temperatura de Debye", "Temperatura de Fermi", "Punto de Boyle", "Punto de Curie"], correcta: 3 },
  { pregunta: "¿Qué enzima une los fragmentos de Okazaki durante la replicación del ADN?", opciones: ["ADN ligasa", "ADN polimerasa I", "Helicasa", "Primasa"], correcta: 0 },
  { pregunta: "¿Cuántos cromosomas tiene un gato doméstico en sus células somáticas?", opciones: ["32", "38", "46", "78"], correcta: 1 },
  { pregunta: "Además de la mitocondria, ¿qué organelo celular posee su propio ADN?", opciones: ["Cloroplasto", "Ribosoma", "Lisosoma", "Aparato de Golgi"], correcta: 0 },
  { pregunta: "¿Cuál de estos procesos ocurre en la matriz mitocondrial?", opciones: ["Ciclo de Krebs", "Glucólisis", "Ciclo de Calvin", "Ciclo de Cori"], correcta: 0 },
  { pregunta: "¿Qué científica determinó por cristalografía la estructura de la penicilina y de la vitamina B12?", opciones: ["Rosalind Franklin", "Marie Curie", "Dorothy Hodgkin", "Barbara McClintock"], correcta: 2 },
  { pregunta: "¿Cuál es la velocidad de escape de la Tierra, aproximadamente?", opciones: ["7,9 km/s", "16,7 km/s", "29,8 km/s", "11,2 km/s"], correcta: 3 },
  { pregunta: "¿Qué luna de Saturno es la única del sistema solar con una atmósfera densa?", opciones: ["Encélado", "Titán", "Rea", "Jápeto"], correcta: 1 },
  { pregunta: "¿Cuál es la estrella más cercana al Sol?", opciones: ["Alfa Centauri A", "Sirio", "Próxima Centauri", "Estrella de Barnard"], correcta: 2 },
  { pregunta: "¿Cómo se llama el límite de masa por encima del cual una enana blanca colapsa?", opciones: ["Límite de Tolman-Oppenheimer-Volkoff", "Radio de Schwarzschild", "Límite de Chandrasekhar", "Límite de Eddington"], correcta: 2 },
  { pregunta: "¿Cuál es la luna más grande de Neptuno?", opciones: ["Nereida", "Proteo", "Tritón", "Larissa"], correcta: 2 },
  { pregunta: "¿Qué telescopio espacial descubrió miles de exoplanetas con el método de tránsito entre 2009 y 2018?", opciones: ["Hubble", "Kepler", "Spitzer", "TESS"], correcta: 1 },
  { pregunta: "¿En qué año se descubrió Plutón?", opciones: ["1915", "1930", "1946", "1951"], correcta: 1 },
  { pregunta: "¿Cuál es el valor aproximado de la constante de Avogadro?", opciones: ["6,626 × 10^-34", "1,602 × 10^-19", "6,022 × 10^23", "9,109 × 10^-31"], correcta: 2 },
  { pregunta: "¿Qué ave viva tiene la mayor envergadura de alas?", opciones: ["Cóndor andino", "Pelícano dálmata", "Albatros errante", "Marabú"], correcta: 2 },
  { pregunta: "¿Qué animal tiene tres corazones?", opciones: ["Medusa", "Estrella de mar", "Pulpo", "Cangrejo"], correcta: 2 },
  { pregunta: "¿Cuál es el hueso más pequeño del cuerpo humano?", opciones: ["Martillo", "Estribo", "Yunque", "Hioides"], correcta: 1 },
  { pregunta: "¿Cuál es el nervio craneal más largo?", opciones: ["Facial", "Trigémino", "Glosofaríngeo", "Vago"], correcta: 3 },
  { pregunta: "¿Qué científico descubrió el sistema de grupos sanguíneos ABO?", opciones: ["Louis Pasteur", "Robert Koch", "Karl Landsteiner", "Paul Ehrlich"], correcta: 2 },
  { pregunta: "¿Cuál es el elemento más abundante en la corteza terrestre?", opciones: ["Silicio", "Oxígeno", "Aluminio", "Hierro"], correcta: 1 },
  { pregunta: "¿Qué mineral tiene dureza 7 en la escala de Mohs?", opciones: ["Topacio", "Ortoclasa", "Cuarzo", "Corindón"], correcta: 2 },
  { pregunta: "¿Cómo se llama la discontinuidad que separa la corteza del manto terrestre?", opciones: ["Gutenberg", "Lehmann", "Mohorovičić", "Conrad"], correcta: 2 },
  { pregunta: "¿Qué escala mide la intensidad de un sismo según sus efectos observados y no su energía?", opciones: ["Richter", "Mercalli", "Beaufort", "Saffir-Simpson"], correcta: 1 },
  { pregunta: "¿Cuál es el gas más abundante en la atmósfera de Venus?", opciones: ["Nitrógeno", "Dióxido de carbono", "Ácido sulfúrico", "Argón"], correcta: 1 },
  { pregunta: "¿Cómo se llama el punto más profundo conocido de los océanos?", opciones: ["Fosa de Puerto Rico", "Fosa de Java", "Fosa de Tonga", "Abismo Challenger"], correcta: 3 },
  { pregunta: "¿Cuál es el desierto más grande del mundo, contando los polares?", opciones: ["Sahara", "Antártico", "Gobi", "Arábigo"], correcta: 1 },
  { pregunta: "¿Cuál es el lago más profundo del mundo?", opciones: ["Baikal", "Tanganica", "Superior", "Titicaca"], correcta: 0 },
  { pregunta: "¿Cuál es el río más largo de Europa?", opciones: ["Danubio", "Rin", "Dniéper", "Volga"], correcta: 3 },
  { pregunta: "¿Qué país tiene más husos horarios en total, contando sus territorios de ultramar?", opciones: ["Rusia", "Estados Unidos", "Francia", "Reino Unido"], correcta: 2 },
  { pregunta: "¿Cuál es la capital de Burkina Faso?", opciones: ["Uagadugú", "Bamako", "Niamey", "Acra"], correcta: 0 },
  { pregunta: "¿Cuál es la capital de Kazajistán?", opciones: ["Astaná", "Almaty", "Taskent", "Biskek"], correcta: 0 },
  { pregunta: "¿Cuál es la capital de Bután?", opciones: ["Timbu", "Katmandú", "Daca", "Colombo"], correcta: 0 },
  { pregunta: "¿Cuál es la capital de Surinam?", opciones: ["Georgetown", "Paramaribo", "Cayena", "Montevideo"], correcta: 1 },
  { pregunta: "¿Cuál es la capital de Mongolia?", opciones: ["Astaná", "Biskek", "Dusambé", "Ulán Bator"], correcta: 3 },
  { pregunta: "¿Cuál es el país más pequeño de África por superficie?", opciones: ["Seychelles", "Gambia", "Mauricio", "Comoras"], correcta: 0 },
  { pregunta: "¿Qué estrecho separa Sicilia de la Italia continental?", opciones: ["Mesina", "Bonifacio", "Otranto", "Gibraltar"], correcta: 0 },
  { pregunta: "¿Cuál es el volcán más alto del mundo sobre el nivel del mar?", opciones: ["Cotopaxi", "Ojos del Salado", "Kilimanjaro", "Popocatépetl"], correcta: 1 },
  { pregunta: "¿Cuál es la isla más grande del mar Mediterráneo?", opciones: ["Cerdeña", "Chipre", "Sicilia", "Creta"], correcta: 2 },
  { pregunta: "¿En qué año cayó Constantinopla en manos de los otomanos?", opciones: ["1204", "1492", "1389", "1453"], correcta: 3 },
  { pregunta: "¿Quién fue el primer emperador de Roma?", opciones: ["Augusto", "Julio César", "Tiberio", "Nerón"], correcta: 0 },
  { pregunta: "¿En qué año se firmó la Paz de Westfalia que cerró la Guerra de los Treinta Años?", opciones: ["1555", "1713", "1815", "1648"], correcta: 3 },
  { pregunta: "¿Qué tratado dividió el Nuevo Mundo entre España y Portugal en 1494?", opciones: ["Tordesillas", "Utrecht", "Verdún", "Versalles"], correcta: 0 },
  { pregunta: "¿Quién fue el último zar de Rusia?", opciones: ["Alejandro III", "Nicolás II", "Pedro III", "Alejandro II"], correcta: 1 },
  { pregunta: "¿Qué dinastía gobernaba China cuando Marco Polo la visitó?", opciones: ["Song", "Ming", "Tang", "Yuan"], correcta: 3 },
  { pregunta: "¿Qué rey inglés firmó la Carta Magna en 1215?", opciones: ["Juan sin Tierra", "Ricardo Corazón de León", "Enrique II", "Eduardo I"], correcta: 0 },
  { pregunta: "¿Cuál fue la capital del Imperio inca?", opciones: ["Machu Picchu", "Quito", "Cusco", "Cajamarca"], correcta: 2 },
  { pregunta: "¿Qué civilización construyó la ciudad de Tiahuanaco, junto al lago Titicaca?", opciones: ["Chavín", "Tiwanaku", "Nazca", "Moche"], correcta: 1 },
  { pregunta: "¿En qué año murió Alejandro Magno?", opciones: ["323 a. C.", "356 a. C.", "331 a. C.", "300 a. C."], correcta: 0 },
  { pregunta: "¿En qué batalla aniquiló Aníbal a un ejército romano en el año 216 a. C.?", opciones: ["Cannas", "Zama", "Trasimeno", "Metauro"], correcta: 0 },
  { pregunta: "¿Quién fue el primer presidente de México?", opciones: ["Agustín de Iturbide", "Guadalupe Victoria", "Vicente Guerrero", "Benito Juárez"], correcta: 1 },
  { pregunta: "¿En qué año se promulgó la Constitución mexicana que sigue vigente?", opciones: ["1857", "1917", "1910", "1824"], correcta: 1 },
  { pregunta: "¿Qué tratado puso fin a la guerra entre México y Estados Unidos en 1848?", opciones: ["Tratado de Córdoba", "Tratado de la Mesilla", "Tratado de Guadalupe Hidalgo", "Tratados de Velasco"], correcta: 2 },
  { pregunta: "¿Quién fue el último tlatoani de Tenochtitlan?", opciones: ["Cuauhtémoc", "Moctezuma II", "Cuitláhuac", "Itzcóatl"], correcta: 0 },
  { pregunta: "¿En qué año se fundó México-Tenochtitlan según la tradición?", opciones: ["1325", "1428", "1492", "1200"], correcta: 0 },
  { pregunta: "¿Qué cultura es considerada la cultura madre de Mesoamérica?", opciones: ["Teotihuacana", "Zapoteca", "Tolteca", "Olmeca"], correcta: 3 },
  { pregunta: "¿Quién lideró la primera fase de la Revolución haitiana?", opciones: ["Toussaint Louverture", "Jean-Jacques Dessalines", "Henri Christophe", "Alexandre Pétion"], correcta: 0 },
  { pregunta: "¿Qué papa convocó la Primera Cruzada en 1095?", opciones: ["Gregorio VII", "Inocencio III", "Urbano II", "León X"], correcta: 2 },
  { pregunta: "¿En qué año ocurrió el Cisma de Oriente entre las Iglesias católica y ortodoxa?", opciones: ["800", "1204", "1378", "1054"], correcta: 3 },
  { pregunta: "¿Qué emperador romano instauró la tetrarquía?", opciones: ["Constantino", "Adriano", "Diocleciano", "Teodosio"], correcta: 2 },
  { pregunta: "¿Quién fue el último emperador del Imperio romano de Occidente?", opciones: ["Rómulo Augústulo", "Odoacro", "Honorio", "Justiniano"], correcta: 0 },
  { pregunta: "¿Qué batalla del año 732 detuvo el avance musulmán hacia el norte de Francia?", opciones: ["Hastings", "Lepanto", "Guadalete", "Poitiers"], correcta: 3 },
  { pregunta: "¿En qué año se libró la batalla naval de Lepanto?", opciones: ["1492", "1588", "1571", "1609"], correcta: 2 },
  { pregunta: "¿En qué año ocurrió el Gran Incendio de Londres?", opciones: ["1605", "1688", "1707", "1666"], correcta: 3 },
  { pregunta: "¿Quién fue el canciller que lideró la unificación alemana de 1871?", opciones: ["Bismarck", "Metternich", "Hindenburg", "Brandt"], correcta: 0 },
  { pregunta: "¿En qué año se disolvió formalmente la Unión Soviética?", opciones: ["1991", "1989", "1990", "1993"], correcta: 0 },
  { pregunta: "¿Qué conferencia de 1884-1885 reguló el reparto colonial de África?", opciones: ["Viena", "Yalta", "Versalles", "Berlín"], correcta: 3 },
  { pregunta: "¿Quién fue el primer secretario general de la ONU?", opciones: ["Dag Hammarskjöld", "U Thant", "Trygve Lie", "Kofi Annan"], correcta: 2 },
  { pregunta: "¿En qué año se fundó la Cruz Roja?", opciones: ["1881", "1901", "1863", "1919"], correcta: 2 },
  { pregunta: "¿Qué faraón mandó construir la Gran Pirámide de Guiza?", opciones: ["Kefrén", "Micerino", "Zoser", "Keops"], correcta: 3 },
  { pregunta: "¿Qué faraón impuso el culto a Atón?", opciones: ["Ramsés II", "Akenatón", "Tutmosis III", "Seti I"], correcta: 1 },
  { pregunta: "¿Quién descifró los jeroglíficos egipcios en 1822?", opciones: ["Thomas Young", "Howard Carter", "Flinders Petrie", "Jean-François Champollion"], correcta: 3 },
  { pregunta: "¿Qué escritura antigua descifró Michael Ventris en 1952?", opciones: ["Lineal B", "Lineal A", "Cuneiforme", "Rongorongo"], correcta: 0 },
  { pregunta: "¿Qué imperio africano gobernó Mansa Musa?", opciones: ["Songhai", "Mali", "Ghana", "Kanem"], correcta: 1 },
  { pregunta: "¿Qué pueblo fundó la ciudad de Cartago?", opciones: ["Fenicios", "Griegos", "Etruscos", "Egipcios"], correcta: 0 },
  { pregunta: "¿Quién fue el primer shogun del shogunato Tokugawa?", opciones: ["Tokugawa Ieyasu", "Oda Nobunaga", "Toyotomi Hideyoshi", "Minamoto no Yoritomo"], correcta: 0 },
  { pregunta: "¿En qué año comenzó la Restauración Meiji en Japón?", opciones: ["1853", "1868", "1894", "1905"], correcta: 1 },
  { pregunta: "¿Qué dinastía construyó la mayor parte de la Gran Muralla china que se conserva hoy?", opciones: ["Qin", "Ming", "Han", "Qing"], correcta: 1 },
  { pregunta: "¿Qué guerra terminó con el Tratado de Nankín de 1842?", opciones: ["Guerra de los Bóxers", "Primera Guerra Sino-Japonesa", "Primera Guerra del Opio", "Rebelión Taiping"], correcta: 2 },
  { pregunta: "¿Qué rey de Prusia es conocido como el Grande?", opciones: ["Federico Guillermo I", "Guillermo I", "Federico III", "Federico II"], correcta: 3 },
  { pregunta: "¿Quién fue el tercer presidente de Estados Unidos?", opciones: ["John Adams", "James Madison", "Thomas Jefferson", "James Monroe"], correcta: 2 },
  { pregunta: "¿Qué presidente de EE. UU. sirvió dos mandatos no consecutivos?", opciones: ["Theodore Roosevelt", "Andrew Johnson", "Martin Van Buren", "Grover Cleveland"], correcta: 3 },
  { pregunta: "¿Qué batalla de 1862 fue el día más sangriento de la historia militar de Estados Unidos?", opciones: ["Gettysburg", "Shiloh", "Antietam", "Bull Run"], correcta: 2 },
  { pregunta: "¿Quién escribió la novela Pedro Páramo?", opciones: ["Carlos Fuentes", "Octavio Paz", "Juan José Arreola", "Juan Rulfo"], correcta: 3 },
  { pregunta: "¿Quién escribió la novela Rayuela?", opciones: ["Mario Vargas Llosa", "Jorge Luis Borges", "Ernesto Sabato", "Julio Cortázar"], correcta: 3 },
  { pregunta: "¿Quién escribió La región más transparente?", opciones: ["Juan Rulfo", "Octavio Paz", "Carlos Fuentes", "Elena Poniatowska"], correcta: 2 },
  { pregunta: "¿Quién ganó el Premio Nobel de Literatura en 1990?", opciones: ["Gabriel García Márquez", "Pablo Neruda", "Octavio Paz", "Camilo José Cela"], correcta: 2 },
  { pregunta: "¿Quién ganó el Premio Nobel de Literatura en 1982?", opciones: ["Mario Vargas Llosa", "Octavio Paz", "Gabriel García Márquez", "Miguel Ángel Asturias"], correcta: 2 },
  { pregunta: "¿Quién ganó el Premio Nobel de Literatura en 1967?", opciones: ["Pablo Neruda", "Gabriela Mistral", "Miguel Ángel Asturias", "Jorge Luis Borges"], correcta: 2 },
  { pregunta: "¿Quién fue la primera persona latinoamericana en ganar el Nobel de Literatura?", opciones: ["Sor Juana Inés de la Cruz", "Gabriela Mistral", "Isabel Allende", "Rosario Castellanos"], correcta: 1 },
  { pregunta: "¿Quién escribió Almas muertas?", opciones: ["Tolstói", "Gógol", "Turguénev", "Chéjov"], correcta: 1 },
  { pregunta: "¿Quién escribió En busca del tiempo perdido?", opciones: ["Marcel Proust", "Flaubert", "Albert Camus", "Balzac"], correcta: 0 },
  { pregunta: "¿Quién escribió Ulises (1922)?", opciones: ["James Joyce", "Virginia Woolf", "Samuel Beckett", "T. S. Eliot"], correcta: 0 },
  { pregunta: "¿Quién escribió El corazón de las tinieblas?", opciones: ["Rudyard Kipling", "Joseph Conrad", "Graham Greene", "E. M. Forster"], correcta: 1 },
  { pregunta: "¿Quién escribió La montaña mágica?", opciones: ["Hermann Hesse", "Thomas Mann", "Franz Kafka", "Robert Musil"], correcta: 1 },
  { pregunta: "¿Quién escribió El lobo estepario?", opciones: ["Thomas Mann", "Rainer Maria Rilke", "Bertolt Brecht", "Hermann Hesse"], correcta: 3 },
  { pregunta: "¿Quién escribió Los hermanos Karamázov?", opciones: ["Tolstói", "Pasternak", "Dostoievski", "Bulgákov"], correcta: 2 },
  { pregunta: "¿Quién escribió El maestro y Margarita?", opciones: ["Pasternak", "Bulgákov", "Gorki", "Solzhenitsyn"], correcta: 1 },
  { pregunta: "¿Cuántos círculos tiene el Infierno en la Divina Comedia de Dante?", opciones: ["9", "7", "10", "12"], correcta: 0 },
  { pregunta: "¿Quién escribió El paraíso perdido?", opciones: ["John Donne", "William Blake", "Alexander Pope", "John Milton"], correcta: 3 },
  { pregunta: "¿En qué obra de Shakespeare aparece el personaje de Yago?", opciones: ["Macbeth", "El rey Lear", "Hamlet", "Otelo"], correcta: 3 },
  { pregunta: "¿Quién pintó Las Meninas?", opciones: ["Velázquez", "Goya", "El Greco", "Murillo"], correcta: 0 },
  { pregunta: "¿Quién pintó El jardín de las delicias?", opciones: ["Brueghel", "Durero", "Van Eyck", "El Bosco"], correcta: 3 },
  { pregunta: "¿Quién pintó La ronda de noche?", opciones: ["Rembrandt", "Vermeer", "Frans Hals", "Rubens"], correcta: 0 },
  { pregunta: "¿Quién pintó el mural El hombre en el cruce de caminos?", opciones: ["José Clemente Orozco", "David Alfaro Siqueiros", "Rufino Tamayo", "Diego Rivera"], correcta: 3 },
  { pregunta: "¿Quién pintó El nacimiento de Venus?", opciones: ["Rafael", "Tiziano", "Giorgione", "Botticelli"], correcta: 3 },
  { pregunta: "¿Quién pintó Impresión, sol naciente?", opciones: ["Manet", "Renoir", "Monet", "Degas"], correcta: 2 },
  { pregunta: "¿Quién esculpió El pensador?", opciones: ["Bernini", "Canova", "Auguste Rodin", "Brancusi"], correcta: 2 },
  { pregunta: "¿Qué arquitecto diseñó la cúpula de Santa Maria del Fiore en Florencia?", opciones: ["Alberti", "Bramante", "Brunelleschi", "Palladio"], correcta: 2 },
  { pregunta: "¿Quién diseñó el Museo Guggenheim de Bilbao?", opciones: ["Zaha Hadid", "Norman Foster", "Renzo Piano", "Frank Gehry"], correcta: 3 },
  { pregunta: "¿Quién compuso Las cuatro estaciones?", opciones: ["Bach", "Corelli", "Vivaldi", "Händel"], correcta: 2 },
  { pregunta: "¿Quién compuso La consagración de la primavera?", opciones: ["Prokófiev", "Chaikovski", "Stravinski", "Shostakóvich"], correcta: 2 },
  { pregunta: "¿Cuántas sinfonías numeradas compuso Mozart?", opciones: ["27", "41", "50", "104"], correcta: 1 },
  { pregunta: "¿Quién compuso la ópera Tosca?", opciones: ["Verdi", "Puccini", "Rossini", "Donizetti"], correcta: 1 },
  { pregunta: "¿Quién compuso El barbero de Sevilla?", opciones: ["Mozart", "Rossini", "Verdi", "Bizet"], correcta: 1 },
  { pregunta: "¿Quién compuso el Bolero?", opciones: ["Debussy", "Satie", "Ravel", "Fauré"], correcta: 2 },
  { pregunta: "¿Qué compositor mexicano escribió Sensemayá?", opciones: ["Carlos Chávez", "Silvestre Revueltas", "Manuel M. Ponce", "Julián Carrillo"], correcta: 1 },
  { pregunta: "¿Quién compuso el vals Sobre las olas?", opciones: ["Agustín Lara", "José Alfredo Jiménez", "Manuel M. Ponce", "Juventino Rosas"], correcta: 3 },
  { pregunta: "¿Cuántas teclas tiene un piano estándar?", opciones: ["76", "88", "92", "96"], correcta: 1 },
  { pregunta: "¿Cómo se llama el intervalo musical de tres tonos enteros, conocido como diabolus in musica?", opciones: ["Quinta justa", "Sexta mayor", "Tritono", "Cuarta justa"], correcta: 2 },
  { pregunta: "¿Quién dirigió El acorazado Potemkin?", opciones: ["Serguéi Eisenstein", "Andréi Tarkovski", "Akira Kurosawa", "Dziga Vertov"], correcta: 0 },
  { pregunta: "¿Quién dirigió Los siete samuráis?", opciones: ["Akira Kurosawa", "Yasujirō Ozu", "Kenji Mizoguchi", "Nagisa Oshima"], correcta: 0 },
  { pregunta: "¿Quién dirigió Amores perros?", opciones: ["Guillermo del Toro", "Alfonso Cuarón", "Carlos Reygadas", "Alejandro G. Iñárritu"], correcta: 3 },
  { pregunta: "¿Quién dirigió Stalker (1979)?", opciones: ["Stanley Kubrick", "Ingmar Bergman", "Federico Fellini", "Andréi Tarkovski"], correcta: 3 },
  { pregunta: "¿Qué película ganó el primer Óscar a la mejor película?", opciones: ["Ben-Hur", "Lo que el viento se llevó", "Casablanca", "Alas"], correcta: 3 },
  { pregunta: "¿Quién dirigió la película Roma (2018)?", opciones: ["Guillermo del Toro", "Alfonso Cuarón", "Alejandro G. Iñárritu", "Carlos Reygadas"], correcta: 1 },
  { pregunta: "¿Cuál es el valor aproximado de i elevado a i, donde i es la unidad imaginaria?", opciones: ["1", "-1", "0,5", "0,2079"], correcta: 3 },
  { pregunta: "¿Cuál es el cuarto número perfecto?", opciones: ["496", "33550336", "1024", "8128"], correcta: 3 },
  { pregunta: "¿Cuál es el décimo número de la sucesión de Fibonacci (1, 1, 2, 3...)?", opciones: ["34", "55", "89", "144"], correcta: 1 },
  { pregunta: "¿Cuántos números primos hay menores que 100?", opciones: ["25", "21", "27", "30"], correcta: 0 },
  { pregunta: "¿Quién demostró el último teorema de Fermat?", opciones: ["Grigori Perelman", "Terence Tao", "Andrew Wiles", "Pierre Deligne"], correcta: 2 },
  { pregunta: "¿Quién demostró la conjetura de Poincaré?", opciones: ["Andrew Wiles", "Grigori Perelman", "Terence Tao", "Stephen Smale"], correcta: 1 },
  { pregunta: "¿Cuál es la suma de los ángulos interiores de un decágono?", opciones: ["1440°", "1260°", "1620°", "1800°"], correcta: 0 },
  { pregunta: "¿Cuánto es 7 factorial (7!)?", opciones: ["720", "40320", "5040", "362880"], correcta: 2 },
  { pregunta: "¿Cuánto es 2 elevado a la 16?", opciones: ["32768", "131072", "65536", "16384"], correcta: 2 },
  { pregunta: "¿Cuántas diagonales tiene un octágono?", opciones: ["20", "16", "24", "28"], correcta: 0 },
  { pregunta: "¿Qué matemático fundó la teoría de conjuntos?", opciones: ["Georg Cantor", "Richard Dedekind", "Bertrand Russell", "Ernst Zermelo"], correcta: 0 },
  { pregunta: "¿Quién demostró los teoremas de incompletitud?", opciones: ["Alan Turing", "David Hilbert", "Alonzo Church", "Kurt Gödel"], correcta: 3 },
  { pregunta: "¿Qué premio, otorgado cada cuatro años a matemáticos menores de 40, se considera el Nobel de las matemáticas?", opciones: ["Premio Abel", "Premio Wolf", "Medalla Fields", "Premio Turing"], correcta: 2 },
  { pregunta: "¿Quién creó el lenguaje de programación C?", opciones: ["Bjarne Stroustrup", "Dennis Ritchie", "Ken Thompson", "James Gosling"], correcta: 1 },
  { pregunta: "¿En qué año se publicó la primera versión del núcleo Linux?", opciones: ["1989", "1995", "1999", "1991"], correcta: 3 },
  { pregunta: "¿Quién inventó la World Wide Web?", opciones: ["Vint Cerf", "Bob Kahn", "Tim Berners-Lee", "Marc Andreessen"], correcta: 2 },
  { pregunta: "¿Qué significan las siglas ASCII?", opciones: ["Advanced System Code for Internet Interfaces", "American Standard Code for Information Interchange", "Automated Standard Coding Interface Index", "American Symbolic Code for Internet Integration"], correcta: 1 },
  { pregunta: "¿Cuántos bits tiene una dirección IPv6?", opciones: ["128", "64", "256", "32"], correcta: 0 },
  { pregunta: "¿Cómo se llamaba la red precursora de Internet creada en 1969?", opciones: ["NSFNET", "ARPANET", "CYCLADES", "Usenet"], correcta: 1 },
  { pregunta: "¿Quién es considerada la primera programadora de la historia?", opciones: ["Grace Hopper", "Ada Lovelace", "Hedy Lamarr", "Margaret Hamilton"], correcta: 1 },
  { pregunta: "¿En qué año venció Deep Blue a Kaspárov en un match de ajedrez?", opciones: ["1989", "1997", "2005", "2011"], correcta: 1 },
  { pregunta: "¿Qué lenguaje de programación lógica creó Alain Colmerauer?", opciones: ["Lisp", "Smalltalk", "Haskell", "Prolog"], correcta: 3 },
  { pregunta: "¿Quién inventó el algoritmo de ordenamiento Quicksort?", opciones: ["Donald Knuth", "Edsger Dijkstra", "Tony Hoare", "John von Neumann"], correcta: 2 },
  { pregunta: "¿Qué científico publicó en 1959 el algoritmo del camino más corto en grafos que lleva su nombre?", opciones: ["Robert Floyd", "Edsger Dijkstra", "Joseph Kruskal", "Robert Prim"], correcta: 1 },
  { pregunta: "¿Cuál es el idioma con más hablantes nativos del mundo?", opciones: ["Inglés", "Español", "Mandarín", "Hindi"], correcta: 2 },
  { pregunta: "¿Qué lengua se suele citar como la de alfabeto más largo del mundo, con 74 letras?", opciones: ["Ruso", "Árabe", "Jemer", "Georgiano"], correcta: 2 },
  { pregunta: "¿A qué familia lingüística pertenece el húngaro?", opciones: ["Urálica", "Indoeuropea", "Altaica", "Túrquica"], correcta: 0 },
  { pregunta: "¿Cuál es la lengua indígena con más hablantes en México?", opciones: ["Maya yucateco", "Náhuatl", "Mixteco", "Zapoteco"], correcta: 1 },
  { pregunta: "¿Cómo se llama la figura retórica que atribuye cualidades humanas a objetos o animales?", opciones: ["Prosopopeya", "Hipérbole", "Metonimia", "Sinécdoque"], correcta: 0 },
  { pregunta: "¿Cuántas sílabas tiene un verso alejandrino?", opciones: ["14", "11", "12", "16"], correcta: 0 },
  { pregunta: "¿Quién es la diosa griega de la venganza y la justicia retributiva?", opciones: ["Hécate", "Némesis", "Eris", "Tique"], correcta: 1 },
  { pregunta: "¿Quién era el barquero que cruzaba las almas por el río Aqueronte?", opciones: ["Caronte", "Cerbero", "Hipnos", "Tánatos"], correcta: 0 },
  { pregunta: "¿Cuál fue el primero de los doce trabajos de Heracles?", opciones: ["Hidra de Lerna", "Jabalí de Erimanto", "Cierva de Cerinea", "León de Nemea"], correcta: 3 },
  { pregunta: "¿Cómo se llama el dios azteca del viento?", opciones: ["Tláloc", "Ehécatl", "Xipe Tótec", "Mictlantecuhtli"], correcta: 1 },
  { pregunta: "¿Cómo se llama el inframundo en la mitología mexica?", opciones: ["Tlalocan", "Mictlán", "Omeyocan", "Tamoanchan"], correcta: 1 },
  { pregunta: "¿Cómo se llama el libro sagrado de los mayas quichés?", opciones: ["Chilam Balam", "Códice Dresde", "Popol Vuh", "Ramayana"], correcta: 2 },
  { pregunta: "¿Qué diosa egipcia con cabeza de leona se asocia a la guerra y la destrucción?", opciones: ["Bastet", "Isis", "Sekhmet", "Hathor"], correcta: 2 },
  { pregunta: "¿Quién es el máximo goleador de la historia de los Mundiales masculinos de fútbol hasta 2022?", opciones: ["Miroslav Klose", "Ronaldo Nazário", "Gerd Müller", "Just Fontaine"], correcta: 0 },
  { pregunta: "¿Qué país ganó el primer Mundial de fútbol, en 1930?", opciones: ["Argentina", "Italia", "Brasil", "Uruguay"], correcta: 3 },
  { pregunta: "¿Quién ganó el Balón de Oro de 1999?", opciones: ["Rivaldo", "Zinedine Zidane", "Luís Figo", "Gabriel Batistuta"], correcta: 0 },
  { pregunta: "¿Qué tenista masculino ganó ocho títulos de Wimbledon?", opciones: ["Pete Sampras", "Roger Federer", "Novak Djokovic", "Björn Borg"], correcta: 1 },
  { pregunta: "¿Quién ganó la final de los 100 metros planos en los Juegos Olímpicos de México 1968?", opciones: ["Jim Hines", "Tommie Smith", "Bob Hayes", "Carl Lewis"], correcta: 0 },
  { pregunta: "¿Cuántos puntos vale un ensayo (try) en rugby union?", opciones: ["5", "3", "4", "6"], correcta: 0 },
  { pregunta: "¿Quién es el campeón mundial de ajedrez más joven de la historia?", opciones: ["Garry Kaspárov", "Magnus Carlsen", "Bobby Fischer", "Gukesh Dommaraju"], correcta: 3 },
  { pregunta: "¿Qué científico descubrió la radiactividad en 1896?", opciones: ["Marie Curie", "Ernest Rutherford", "Wilhelm Röntgen", "Henri Becquerel"], correcta: 3 },
  { pregunta: "¿Quién descubrió el electrón en 1897?", opciones: ["J. J. Thomson", "Ernest Rutherford", "Niels Bohr", "Robert Millikan"], correcta: 0 },
  { pregunta: "¿Quién descubrió el neutrón en 1932?", opciones: ["Enrico Fermi", "Paul Dirac", "Hans Geiger", "James Chadwick"], correcta: 3 },
  { pregunta: "¿Cómo se llama el isótopo del hidrógeno con un protón y dos neutrones?", opciones: ["Tritio", "Deuterio", "Protio", "Helio-3"], correcta: 0 },
  { pregunta: "¿Cuál es el gas noble más abundante en la atmósfera terrestre?", opciones: ["Neón", "Helio", "Kriptón", "Argón"], correcta: 3 },
  { pregunta: "¿Qué elemento químico se representa con el símbolo W?", opciones: ["Vanadio", "Xenón", "Berilio", "Wolframio"], correcta: 3 },
  { pregunta: "¿Qué elemento químico se representa con el símbolo Sb?", opciones: ["Estroncio", "Antimonio", "Azufre", "Selenio"], correcta: 1 },
  { pregunta: "¿Cuál es el elemento sintético con número atómico 43?", opciones: ["Tecnecio", "Prometio", "Astato", "Francio"], correcta: 0 },
  { pregunta: "¿Cuál es el pH normal aproximado de la sangre humana?", opciones: ["6,8", "7,4", "8,2", "5,5"], correcta: 1 },
  { pregunta: "¿Qué ley relaciona la presión y el volumen de un gas a temperatura constante?", opciones: ["Ley de Charles", "Ley de Boyle", "Ley de Gay-Lussac", "Ley de Avogadro"], correcta: 1 },
  { pregunta: "¿Cuál es la unidad del Sistema Internacional para la inductancia?", opciones: ["Faradio", "Weber", "Tesla", "Henrio"], correcta: 3 },
  { pregunta: "¿Cuál es la unidad del Sistema Internacional para el flujo magnético?", opciones: ["Tesla", "Gauss", "Weber", "Henrio"], correcta: 2 },
  { pregunta: "¿Qué experimento de 1887 no logró detectar el éter luminífero?", opciones: ["Young", "Millikan", "Michelson-Morley", "Davisson-Germer"], correcta: 2 },
  { pregunta: "¿Qué físico predijo teóricamente la existencia de la antimateria?", opciones: ["Paul Dirac", "Erwin Schrödinger", "Max Born", "Niels Bohr"], correcta: 0 },
  { pregunta: "¿En qué año se anunció el descubrimiento del bosón de Higgs?", opciones: ["2012", "2008", "2010", "2015"], correcta: 0 },
  { pregunta: "¿Qué observatorio detectó por primera vez ondas gravitacionales?", opciones: ["VIRGO", "ALMA", "LIGO", "Arecibo"], correcta: 2 },
  { pregunta: "¿Cómo es la duración del día de rotación de Venus comparada con su año?", opciones: ["Igual que su año", "Más larga que su año", "Mucho más corta", "La mitad de su año"], correcta: 1 },
  { pregunta: "¿Qué planeta gira prácticamente de lado, con una inclinación axial de unos 98°?", opciones: ["Neptuno", "Saturno", "Marte", "Urano"], correcta: 3 },
  { pregunta: "¿Cuál es el cuerpo más grande del cinturón de asteroides?", opciones: ["Vesta", "Palas", "Higía", "Ceres"], correcta: 3 },
  { pregunta: "¿Cómo se llama la nube hipotética de cometas en el borde del sistema solar?", opciones: ["Cinturón de Kuiper", "Heliopausa", "Nube de Oort", "Disco disperso"], correcta: 2 },
  { pregunta: "¿Qué sonda fue la primera en cruzar la heliopausa?", opciones: ["Pioneer 10", "Voyager 2", "New Horizons", "Voyager 1"], correcta: 3 },
  { pregunta: "¿Quién fue la primera mujer en viajar al espacio?", opciones: ["Sally Ride", "Valentina Tereshkova", "Svetlana Savítskaya", "Mae Jemison"], correcta: 1 },
  { pregunta: "¿Quién fue el primer mexicano en viajar al espacio?", opciones: ["Rodolfo Neri Vela", "José Hernández", "Franklin Chang", "Carlos Noriega"], correcta: 0 },
  { pregunta: "¿Cuántos pares de nervios raquídeos tiene el ser humano?", opciones: ["12", "24", "33", "31"], correcta: 3 },
  { pregunta: "¿Qué glándula secreta la melatonina?", opciones: ["Hipófisis", "Pineal", "Tiroides", "Suprarrenal"], correcta: 1 },
  { pregunta: "¿Qué hormona secretada por el tejido adiposo regula la sensación de saciedad?", opciones: ["Grelina", "Cortisol", "Leptina", "Glucagón"], correcta: 2 },
  { pregunta: "¿Qué bióloga impulsó la teoría endosimbiótica moderna del origen de las células eucariotas?", opciones: ["Barbara McClintock", "Rachel Carson", "Jane Goodall", "Lynn Margulis"], correcta: 3 },
  { pregunta: "¿Qué mexicano ganó el Premio Nobel de Química en 1995?", opciones: ["Luis Alvarez", "Octavio Paz", "Mario Molina", "Alfonso García Robles"], correcta: 2 },
  { pregunta: "¿Qué mexicano ganó el Premio Nobel de la Paz en 1982?", opciones: ["Mario Molina", "Alfonso García Robles", "Octavio Paz", "Luis Echeverría"], correcta: 1 },
  { pregunta: "¿Qué país tiene más islas en el mundo?", opciones: ["Indonesia", "Filipinas", "Canadá", "Suecia"], correcta: 3 },
  { pregunta: "¿Qué país tiene más lagos en el mundo?", opciones: ["Finlandia", "Rusia", "Estados Unidos", "Canadá"], correcta: 3 },
  { pregunta: "¿Cuál es la capital soberana más septentrional del mundo?", opciones: ["Oslo", "Helsinki", "Estocolmo", "Reikiavik"], correcta: 3 },
  { pregunta: "¿Qué país africano evitó la colonización europea, salvo una breve ocupación italiana?", opciones: ["Etiopía", "Ghana", "Nigeria", "Kenia"], correcta: 0 },
  { pregunta: "¿Qué país tiene la mayor población musulmana del mundo?", opciones: ["Pakistán", "Indonesia", "India", "Egipto"], correcta: 1 },
  { pregunta: "¿Cuál es la moneda de Polonia?", opciones: ["Esloti", "Corona", "Forinto", "Leu"], correcta: 0 },
  { pregunta: "¿Cuál es la moneda de Tailandia?", opciones: ["Baht", "Dong", "Kip", "Ringgit"], correcta: 0 },
  { pregunta: "¿Qué cordillera separa convencionalmente Europa de Asia?", opciones: ["Cáucaso", "Cárpatos", "Alpes", "Urales"], correcta: 3 },
  { pregunta: "¿Qué mar es el único del mundo que no tiene costas?", opciones: ["Mar Muerto", "Mar Caspio", "Mar de los Sargazos", "Mar de Aral"], correcta: 2 },
  { pregunta: "¿Qué especie de árbol alcanza la mayor altura del mundo?", opciones: ["Eucalipto regnans", "Secuoya roja", "Abeto de Douglas", "Baobab"], correcta: 1 },
  { pregunta: "¿Qué planta produce la flor individual más grande del mundo?", opciones: ["Rafflesia arnoldii", "Amorphophallus titanum", "Victoria amazonica", "Nelumbo nucifera"], correcta: 0 },
  { pregunta: "¿Qué mamífero tiene uno de los periodos de gestación más largos, de cerca de 22 meses?", opciones: ["Ballena azul", "Rinoceronte", "Jirafa", "Elefante africano"], correcta: 3 },
  { pregunta: "¿Qué mamífero pone huevos además del ornitorrinco?", opciones: ["Pangolín", "Equidna", "Armadillo", "Cebra"], correcta: 1 },
  { pregunta: "¿Qué vertebrado es el más longevo que se conoce, con unos 400 años de vida?", opciones: ["Tortuga de Galápagos", "Ballena de Groenlandia", "Carpa koi", "Tiburón de Groenlandia"], correcta: 3 },
  { pregunta: "¿Cuál es el volcán más alto de México?", opciones: ["Popocatépetl", "Pico de Orizaba", "Iztaccíhuatl", "Nevado de Toluca"], correcta: 1 },
  { pregunta: "¿Cuál es el estado más grande de México por superficie?", opciones: ["Chihuahua", "Sonora", "Coahuila", "Baja California"], correcta: 0 },
  { pregunta: "¿Cuál es el estado más pequeño de México por superficie?", opciones: ["Tlaxcala", "Morelos", "Aguascalientes", "Colima"], correcta: 0 },
  { pregunta: "¿Quién escribió la letra del Himno Nacional Mexicano?", opciones: ["Jaime Nunó", "Manuel Acuña", "Amado Nervo", "Francisco González Bocanegra"], correcta: 3 },
  { pregunta: "¿Quién compuso la música del Himno Nacional Mexicano?", opciones: ["Miguel Lerdo de Tejada", "Juventino Rosas", "Jaime Nunó", "Ricardo Castro"], correcta: 2 }
];
