export const PREGUNTAS = [
  { pregunta: "¿Cuál es el planeta más grande del sistema solar?", opciones: ["Marte", "Júpiter", "Saturno", "Tierra"], correcta: 1 },
  { pregunta: "¿En qué año llegó el ser humano a la Luna?", opciones: ["1965", "1969", "1972", "1959"], correcta: 1 },
  { pregunta: "¿Cuál es el océano más grande del mundo?", opciones: ["Atlántico", "Índico", "Pacífico", "Ártico"], correcta: 2 },
  { pregunta: "¿Cuántos huesos tiene el cuerpo humano adulto?", opciones: ["186", "206", "220", "250"], correcta: 1 },
  { pregunta: "¿Qué gas respiramos principalmente para vivir?", opciones: ["Oxígeno", "Hidrógeno", "Nitrógeno", "Dióxido de carbono"], correcta: 0 },
  { pregunta: "¿Cuál es el país más grande del mundo por territorio?", opciones: ["China", "Canadá", "Rusia", "Brasil"], correcta: 2 },
  { pregunta: "¿Cuál es el río más caudaloso de Sudamérica?", opciones: ["Orinoco", "Amazonas", "Paraná", "Magdalena"], correcta: 1 },
  { pregunta: "¿Quién pintó la Mona Lisa?", opciones: ["Miguel Ángel", "Rafael", "Leonardo da Vinci", "Botticelli"], correcta: 2 },
  { pregunta: "¿Qué elemento químico se representa con el símbolo Au?", opciones: ["Plata", "Oro", "Aluminio", "Argón"], correcta: 1 },
  { pregunta: "¿Cuántos lados tiene un hexágono?", opciones: ["Cinco", "Seis", "Siete", "Ocho"], correcta: 1 },
  { pregunta: "¿En qué continente se encuentra Egipto?", opciones: ["Asia", "Europa", "África", "Oceanía"], correcta: 2 },
  { pregunta: "¿Cuál es el animal terrestre más veloz?", opciones: ["León", "Guepardo", "Caballo", "Antílope"], correcta: 1 },
  { pregunta: "¿Cuál es la capital de Japón?", opciones: ["Osaka", "Kioto", "Tokio", "Nagoya"], correcta: 2 },
  { pregunta: "¿Cuántos jugadores de un mismo equipo están en el campo durante un partido de fútbol?", opciones: ["Nueve", "Diez", "Once", "Doce"], correcta: 2 },
  { pregunta: "¿Qué órgano se encarga de bombear la sangre en el cuerpo humano?", opciones: ["Pulmón", "Hígado", "Riñón", "Corazón"], correcta: 3 },
  { pregunta: "¿Cuál es el planeta más cercano al Sol?", opciones: ["Venus", "Mercurio", "Marte", "Tierra"], correcta: 1 },
  { pregunta: "¿Quién escribió \"Don Quijote de la Mancha\"?", opciones: ["Lope de Vega", "Miguel de Cervantes", "Francisco de Quevedo", "Gabriel García Márquez"], correcta: 1 },
  { pregunta: "¿Qué metal es líquido a temperatura ambiente?", opciones: ["Plomo", "Estaño", "Mercurio", "Zinc"], correcta: 2 },
  { pregunta: "¿En qué año comenzó la Primera Guerra Mundial?", opciones: ["1905", "1914", "1918", "1939"], correcta: 1 },
  { pregunta: "¿Cuál es la capital de Australia?", opciones: ["Sídney", "Melbourne", "Canberra", "Perth"], correcta: 2 },
  { pregunta: "¿Cuántos minutos hay en una hora y media?", opciones: ["75", "80", "90", "100"], correcta: 2 },
  { pregunta: "¿Cuál es el hueso más largo del cuerpo humano?", opciones: ["Húmero", "Fémur", "Tibia", "Radio"], correcta: 1 },
  { pregunta: "¿Cuál es el símbolo químico del agua?", opciones: ["H2O", "CO2", "O2", "NaCl"], correcta: 0 },
  { pregunta: "¿Qué planeta es conocido como el planeta rojo?", opciones: ["Júpiter", "Venus", "Marte", "Saturno"], correcta: 2 }
];
